ktor:
  application:
    modules:
      - com.dabelyu.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0
  database:
    url: "jdbc:postgresql://localhost:5432/test_db"
    driver: "org.postgresql.Driver"
    user: "postgres"
    password: "password"
